[package]
name = "cli"
version = "0.1.1"
edition = "2021"
description = "Snowflake emulator CLI"

[[bin]]
name = "snowflake-emulator"
path = "src/main.rs"

[dependencies]
server = { path = "../server" }
tokio.workspace = true
tracing-subscriber.workspace = true
